import type { NGO } from '@/types';

export const ngos: NGO[] = [
  {
    id: 'ngo_001',
    name: 'Educate for All',
    ownerId: 'placeholder_owner',
    shortDescription: 'Quality education for underprivileged children.',
    description: 'Educate for All is dedicated to breaking the cycle of poverty by providing quality education, resources, and support to children in need. We operate in several remote regions, building schools and providing necessary learning materials.',
    city: 'Delhi',
    state: 'Delhi',
    cause: 'Education',
    impactScore: 88,
    image: 'ngo_001',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 100000,
    raisedAmount: 45000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_002',
    name: 'Green Planet Initiative',
    ownerId: 'placeholder_owner',
    shortDescription: 'Working towards a sustainable future.',
    description: 'Green Planet Initiative focuses on reforestation projects, promoting sustainable agriculture, and advocating for policies that protect our environment. Join us in making our planet greener.',
    city: 'Multiple Cities',
    state: 'Maharashtra',
    cause: 'Environment',
    impactScore: 92,
    image: 'ngo_002',
    icon: 'TreePine',
    verified: true,
    goalAmount: 250000,
    raisedAmount: 180000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_003',
    name: 'HealthBridge',
    ownerId: 'placeholder_owner',
    shortDescription: 'Accessible healthcare for remote communities.',
    description: 'HealthBridge provides essential medical services, health education, and emergency care to communities that lack access to basic healthcare facilities. Our mobile clinics reach the most isolated areas.',
    city: 'Bangalore',
    state: 'Karnataka',
    cause: 'Healthcare',
    impactScore: 85,
    image: 'ngo_003',
    icon: 'Heart',
    verified: true,
    goalAmount: 500000,
    raisedAmount: 320000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_004',
    name: 'Safe Haven Animal Rescue',
    ownerId: 'placeholder_owner',
    shortDescription: 'Protecting and rehoming animals in need.',
    description: 'Safe Haven Animal Rescue is committed to rescuing abandoned and abused animals, providing them with medical care, and finding them loving forever homes. We also run awareness campaigns on animal welfare.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Animal Welfare',
    impactScore: 90,
    image: 'ngo_004',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 150000,
    raisedAmount: 95000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_005',
    name: 'The Empowerment Project',
    ownerId: 'placeholder_owner',
    shortDescription: 'Supporting women and girls to achieve their potential.',
    description: 'The Empowerment Project provides vocational training, financial literacy, and mentorship programs for women and girls from marginalized communities, helping them become economically independent and confident.',
    city: 'Kolkata',
    state: 'West Bengal',
    cause: 'Women Empowerment',
    impactScore: 89,
    image: 'ngo_005',
    icon: 'Globe',
    verified: true,
    goalAmount: 300000,
    raisedAmount: 120000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_006',
    name: 'Child Rights and You (CRY)',
    ownerId: 'placeholder_owner',
    shortDescription: 'Ensuring happier childhoods for every child.',
    description: 'CRY addresses children’s critical needs by working with parents, teachers, Anganwadi workers, communities, district and state-level governments, as well as the children themselves.',
    city: 'Multiple Cities',
    state: 'Multiple States',
    cause: 'Child Rights',
    impactScore: 94,
    image: 'ngo_006',
    icon: 'Globe',
    verified: true,
    goalAmount: 1000000,
    raisedAmount: 750000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_007',
    name: 'Smile Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Healthcare and education for children and families.',
    description: 'Smile Foundation is a national level development organisation directly benefitting over 1.5 million children and their families every year, through more than 400 live welfare projects on education, healthcare, livelihood and women empowerment.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Healthcare',
    impactScore: 91,
    image: 'ngo_007',
    icon: 'Heart',
    verified: true,
    goalAmount: 800000,
    raisedAmount: 620000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_008',
    name: 'GiveIndia Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Connecting donors with credible NGOs.',
    description: 'GiveIndia is India’s largest and most trustworthy giving platform for donors. Our community of 2M+ donors and 250+ partners have supported 2,500+ verified nonprofits, serving 15M+ people across India.',
    city: 'Bangalore',
    state: 'Karnataka',
    cause: 'Community Development',
    impactScore: 88,
    image: 'ngo_008',
    icon: 'Globe',
    verified: true,
    goalAmount: 2000000,
    raisedAmount: 1500000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_009',
    name: 'Goonj',
    ownerId: 'placeholder_owner',
    shortDescription: 'A resource for rural development and disaster relief.',
    description: 'Goonj is a non-governmental organisation headquartered in New Delhi, India which undertakes disaster relief, humanitarian aid and community development in parts of 23 states across India.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Disaster Relief',
    impactScore: 93,
    image: 'ngo_009',
    icon: 'Heart',
    verified: true,
    goalAmount: 1200000,
    raisedAmount: 900000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_010',
    name: 'HelpAge India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Fighting for the rights of the elderly.',
    description: 'HelpAge India is a leading charity in India working with and for disadvantaged elderly for more than 4 decades. It was set up in 1978 and is a member of the HelpAge Global Network.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Elderly Care',
    impactScore: 89,
    image: 'ngo_010',
    icon: 'Heart',
    verified: true,
    goalAmount: 600000,
    raisedAmount: 420000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_011',
    name: 'Narayan Seva Sansthan',
    ownerId: 'placeholder_owner',
    shortDescription: 'Disability support and rehabilitation services.',
    description: 'Narayan Seva Sansthan provides free corrective surgeries, rehabilitation, and vocational support for people with disabilities to help them live with dignity and independence.',
    city: 'Udaipur',
    state: 'Rajasthan',
    cause: 'Disability Support',
    impactScore: 92,
    image: 'ngo_011',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 750000,
    raisedAmount: 515000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_012',
    name: 'Aravind Eye Care System',
    ownerId: 'placeholder_owner',
    shortDescription: 'Eye care and blindness treatment.',
    description: 'Aravind Eye Care System is one of the world\'s largest eye care providers, delivering affordable eye surgeries, screenings, and blindness prevention at scale.',
    city: 'Madurai',
    state: 'Tamil Nadu',
    cause: 'Healthcare',
    impactScore: 95,
    image: 'ngo_012',
    icon: 'Heart',
    verified: true,
    goalAmount: 900000,
    raisedAmount: 680000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_013',
    name: 'Sightsavers India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Eye health and avoidable blindness prevention.',
    description: 'Sightsavers India works on eye health, cataract surgery access, and inclusive development programs that prevent avoidable blindness.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Healthcare',
    impactScore: 90,
    image: 'ngo_013',
    icon: 'Heart',
    verified: true,
    goalAmount: 650000,
    raisedAmount: 430000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_014',
    name: 'CanKids KidsCan',
    ownerId: 'placeholder_owner',
    shortDescription: 'Support for children battling cancer.',
    description: 'CanKids KidsCan provides holistic support for children with cancer and their families, including treatment assistance, shelter, nutrition, and emotional care.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Healthcare',
    impactScore: 89,
    image: 'ngo_014',
    icon: 'Heart',
    verified: true,
    goalAmount: 700000,
    raisedAmount: 395000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_015',
    name: 'Lepra Society',
    ownerId: 'placeholder_owner',
    shortDescription: 'Health, leprosy care, and HIV/AIDS support.',
    description: 'Lepra Society works to eliminate leprosy-related disability, improve health access, and support communities affected by stigma and exclusion.',
    city: 'Hyderabad',
    state: 'Telangana',
    cause: 'Healthcare',
    impactScore: 87,
    image: 'ngo_015',
    icon: 'Heart',
    verified: true,
    goalAmount: 550000,
    raisedAmount: 310000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_016',
    name: 'MOHAN Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Organ donation awareness and healthcare support.',
    description: 'MOHAN Foundation promotes organ donation awareness and helps build systems that improve transplant access and healthcare education.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    cause: 'Healthcare',
    impactScore: 88,
    image: 'ngo_016',
    icon: 'Heart',
    verified: true,
    goalAmount: 500000,
    raisedAmount: 280000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_017',
    name: 'CBM India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Disability inclusion and healthcare.',
    description: 'CBM India advances disability inclusion through healthcare access, community-based rehabilitation, and advocacy for equal opportunity.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Disability Support',
    impactScore: 89,
    image: 'ngo_017',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 600000,
    raisedAmount: 355000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_018',
    name: 'Samarthanam Trust for the Disabled',
    ownerId: 'placeholder_owner',
    shortDescription: 'Disability support and inclusive education.',
    description: 'Samarthanam Trust for the Disabled supports accessibility, education, livelihoods, and sports opportunities for people with disabilities.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Disability Support',
    impactScore: 88,
    image: 'ngo_018',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 580000,
    raisedAmount: 300000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_019',
    name: 'National Association for the Blind',
    ownerId: 'placeholder_owner',
    shortDescription: 'Blindness support and education.',
    description: 'The National Association for the Blind provides education, rehabilitation, and employment support for visually impaired individuals.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Disability Support',
    impactScore: 90,
    image: 'ngo_019',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 640000,
    raisedAmount: 410000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_020',
    name: 'Pratham',
    ownerId: 'placeholder_owner',
    shortDescription: 'Children\'s education and learning outcomes.',
    description: 'Pratham works to improve literacy, numeracy, and foundational learning for children across India through scalable education programs.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Education',
    impactScore: 94,
    image: 'ngo_020',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 850000,
    raisedAmount: 620000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_021',
    name: 'Teach For India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Education leadership and classroom support.',
    description: 'Teach For India recruits and trains leaders to work in classrooms and improve learning outcomes for children from underserved communities.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Education',
    impactScore: 91,
    image: 'ngo_021',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 900000,
    raisedAmount: 540000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_022',
    name: 'Akanksha Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Education for underprivileged children.',
    description: 'Akanksha Foundation supports children from low-income communities through school partnerships, teacher development, and holistic learning support.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Education',
    impactScore: 88,
    image: 'ngo_022',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 500000,
    raisedAmount: 265000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_023',
    name: 'eVidyaloka',
    ownerId: 'placeholder_owner',
    shortDescription: 'Digital education for rural learners.',
    description: 'eVidyaloka enables remote teaching for rural government schools by connecting volunteer teachers with classrooms through technology.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Education',
    impactScore: 87,
    image: 'ngo_023',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 420000,
    raisedAmount: 210000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_024',
    name: 'Agastya International Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'STEM and experiential learning.',
    description: 'Agastya International Foundation promotes hands-on science learning, innovation, and curiosity-driven education for children and teachers.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Education',
    impactScore: 90,
    image: 'ngo_024',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 780000,
    raisedAmount: 470000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_025',
    name: 'Nanhi Kali',
    ownerId: 'placeholder_owner',
    shortDescription: 'Girl child education and support.',
    description: 'Nanhi Kali supports girls\' education through learning materials, mentoring, and long-term school retention support.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Education',
    impactScore: 89,
    image: 'ngo_025',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 600000,
    raisedAmount: 370000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_026',
    name: 'Aangan Trust',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child protection and anti-trafficking.',
    description: 'Aangan Trust works to protect vulnerable children, prevent trafficking, and build safer community systems for child protection.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Child Rights',
    impactScore: 88,
    image: 'ngo_026',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 480000,
    raisedAmount: 260000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_027',
    name: 'Butterflies India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Support for children and human rights.',
    description: 'Butterflies India supports street and working children through education, health, and rights-based social protection programs.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Child Rights',
    impactScore: 86,
    image: 'ngo_027',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 360000,
    raisedAmount: 180000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_028',
    name: 'Centre for Science and Environment',
    ownerId: 'placeholder_owner',
    shortDescription: 'Environment and public policy research.',
    description: 'The Centre for Science and Environment drives policy research, advocacy, and public awareness for sustainable environmental development.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Environment',
    impactScore: 91,
    image: 'ngo_028',
    icon: 'TreePine',
    verified: true,
    goalAmount: 700000,
    raisedAmount: 410000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_029',
    name: 'TERI',
    ownerId: 'placeholder_owner',
    shortDescription: 'Energy, sustainability, and environment.',
    description: 'TERI works on energy efficiency, climate solutions, and sustainability research that supports policy and community impact.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Environment',
    impactScore: 93,
    image: 'ngo_029',
    icon: 'TreePine',
    verified: true,
    goalAmount: 900000,
    raisedAmount: 640000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_030',
    name: 'WWF India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Wildlife and conservation.',
    description: 'WWF India focuses on wildlife conservation, habitat protection, and conservation education across ecosystems and communities.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Environment',
    impactScore: 94,
    image: 'ngo_030',
    icon: 'TreePine',
    verified: true,
    goalAmount: 950000,
    raisedAmount: 700000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_031',
    name: 'Greenpeace India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Climate action and environmental advocacy.',
    description: 'Greenpeace India campaigns for climate justice, renewable energy, and environmental protection through public advocacy and research.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Environment',
    impactScore: 90,
    image: 'ngo_031',
    icon: 'TreePine',
    verified: true,
    goalAmount: 720000,
    raisedAmount: 420000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_032',
    name: 'Wildlife SOS',
    ownerId: 'placeholder_owner',
    shortDescription: 'Wildlife rescue and protection.',
    description: 'Wildlife SOS rescues and rehabilitates wild animals while working to reduce human-wildlife conflict and protect endangered species.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Environment',
    impactScore: 92,
    image: 'ngo_032',
    icon: 'TreePine',
    verified: true,
    goalAmount: 800000,
    raisedAmount: 560000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_033',
    name: 'SayTrees',
    ownerId: 'placeholder_owner',
    shortDescription: 'Tree plantation and ecological restoration.',
    description: 'SayTrees leads community tree-planting and restoration efforts to improve green cover, biodiversity, and climate resilience.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Environment',
    impactScore: 88,
    image: 'ngo_033',
    icon: 'TreePine',
    verified: true,
    goalAmount: 340000,
    raisedAmount: 180000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_034',
    name: 'Sanctuary Nature Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Wildlife and conservation awareness.',
    description: 'Sanctuary Nature Foundation promotes conservation awareness, wildlife protection, and ecological education through media and outreach.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Environment',
    impactScore: 85,
    image: 'ngo_034',
    icon: 'TreePine',
    verified: true,
    goalAmount: 300000,
    raisedAmount: 150000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_035',
    name: 'SEWA',
    ownerId: 'placeholder_owner',
    shortDescription: 'Women workers, livelihoods, and empowerment.',
    description: 'SEWA organizes women workers in the informal economy to support livelihoods, rights, financial inclusion, and collective empowerment.',
    city: 'Ahmedabad',
    state: 'Gujarat',
    cause: 'Women Empowerment',
    impactScore: 93,
    image: 'ngo_035',
    icon: 'Globe',
    verified: true,
    goalAmount: 750000,
    raisedAmount: 500000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_036',
    name: 'Snehalaya',
    ownerId: 'placeholder_owner',
    shortDescription: 'Support for women, children, and HIV care.',
    description: 'Snehalaya supports women and children affected by exploitation, abuse, and HIV through shelter, education, and rehabilitation programs.',
    city: 'Ahmednagar',
    state: 'Maharashtra',
    cause: 'Women Empowerment',
    impactScore: 87,
    image: 'ngo_036',
    icon: 'Globe',
    verified: true,
    goalAmount: 420000,
    raisedAmount: 220000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_037',
    name: 'Jagori',
    ownerId: 'placeholder_owner',
    shortDescription: 'Women\'s rights and gender equality.',
    description: 'Jagori works on gender equality, safety, rights awareness, and strengthening women\'s leadership and community participation.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Women Empowerment',
    impactScore: 88,
    image: 'ngo_037',
    icon: 'Globe',
    verified: true,
    goalAmount: 380000,
    raisedAmount: 195000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_038',
    name: 'Breakthrough India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Gender equality and violence prevention.',
    description: 'Breakthrough India uses campaigns and community programs to challenge violence, promote equality, and build safe spaces for women and girls.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Women Empowerment',
    impactScore: 90,
    image: 'ngo_038',
    icon: 'Globe',
    verified: true,
    goalAmount: 560000,
    raisedAmount: 330000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_039',
    name: 'Azad Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Women\'s livelihoods and skills training.',
    description: 'Azad Foundation trains women for safe and sustainable livelihoods while promoting agency, mobility, and economic independence.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Women Empowerment',
    impactScore: 86,
    image: 'ngo_039',
    icon: 'Globe',
    verified: true,
    goalAmount: 320000,
    raisedAmount: 160000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_040',
    name: 'Sakhi',
    ownerId: 'placeholder_owner',
    shortDescription: 'Women\'s support and safety services.',
    description: 'Sakhi provides support services, counseling, and safety-focused interventions for women facing violence and vulnerability.',
    city: 'Pune',
    state: 'Maharashtra',
    cause: 'Women Empowerment',
    impactScore: 84,
    image: 'ngo_040',
    icon: 'Globe',
    verified: true,
    goalAmount: 290000,
    raisedAmount: 140000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_041',
    name: 'Akshaya Patra Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Mid-day meals and child nutrition.',
    description: 'Akshaya Patra Foundation delivers nutritious mid-day meals to schoolchildren and supports child nutrition and attendance.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Child Nutrition',
    impactScore: 95,
    image: 'ngo_041',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 1000000,
    raisedAmount: 780000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_042',
    name: 'Annamrita Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child nutrition and school meals.',
    description: 'Annamrita Foundation works to reduce child hunger by serving nutritious school meals and supporting education access.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Child Nutrition',
    impactScore: 89,
    image: 'ngo_042',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 480000,
    raisedAmount: 250000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_043',
    name: 'Robin Hood Army',
    ownerId: 'placeholder_owner',
    shortDescription: 'Hunger relief and food redistribution.',
    description: 'Robin Hood Army is a volunteer-driven movement that redistributes surplus food to communities and fights hunger with a local network.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Hunger Relief',
    impactScore: 91,
    image: 'ngo_043',
    icon: 'Globe',
    verified: true,
    goalAmount: 430000,
    raisedAmount: 210000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_044',
    name: 'Gram Vikas',
    ownerId: 'placeholder_owner',
    shortDescription: 'Rural development, sanitation, and water.',
    description: 'Gram Vikas supports rural communities with water, sanitation, livelihoods, and participatory village development programs.',
    city: 'Bhubaneswar',
    state: 'Odisha',
    cause: 'Rural Development',
    impactScore: 90,
    image: 'ngo_044',
    icon: 'Globe',
    verified: true,
    goalAmount: 610000,
    raisedAmount: 340000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_045',
    name: 'Barefoot College',
    ownerId: 'placeholder_owner',
    shortDescription: 'Rural livelihoods and solar training.',
    description: 'Barefoot College empowers rural communities through solar training, education, and women-led livelihood opportunities.',
    city: 'Tilonia',
    state: 'Rajasthan',
    cause: 'Rural Development',
    impactScore: 92,
    image: 'ngo_045',
    icon: 'TreePine',
    verified: true,
    goalAmount: 520000,
    raisedAmount: 295000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_046',
    name: 'Digital Empowerment Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Digital inclusion and rural empowerment.',
    description: 'Digital Empowerment Foundation brings digital access, training, and local enterprise support to underserved communities.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Digital Inclusion',
    impactScore: 88,
    image: 'ngo_046',
    icon: 'Globe',
    verified: true,
    goalAmount: 400000,
    raisedAmount: 215000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_047',
    name: 'The Nudge Institute',
    ownerId: 'placeholder_owner',
    shortDescription: 'Poverty alleviation and livelihood support.',
    description: 'The Nudge Institute builds programs that help vulnerable communities escape poverty through income, skilling, and support systems.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Poverty Alleviation',
    impactScore: 93,
    image: 'ngo_047',
    icon: 'Globe',
    verified: true,
    goalAmount: 880000,
    raisedAmount: 560000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_048',
    name: 'World Vision India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child welfare and poverty relief.',
    description: 'World Vision India supports children and communities through relief, education, health, and long-term development programs.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    cause: 'Child Welfare',
    impactScore: 90,
    image: 'ngo_048',
    icon: 'Heart',
    verified: true,
    goalAmount: 760000,
    raisedAmount: 430000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_049',
    name: 'Deepalaya',
    ownerId: 'placeholder_owner',
    shortDescription: 'Education and child development.',
    description: 'Deepalaya works to improve education, health, and development opportunities for marginalized children and families.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Education',
    impactScore: 87,
    image: 'ngo_049',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 420000,
    raisedAmount: 220000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_050',
    name: 'Save the Children India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child rights, education, and health.',
    description: 'Save the Children India supports children with education, healthcare, protection, and emergency relief interventions.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Child Rights',
    impactScore: 92,
    image: 'ngo_050',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 970000,
    raisedAmount: 610000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_051',
    name: 'Magic Bus India Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Youth development and employability.',
    description: 'Magic Bus India Foundation helps young people transition from childhood to livelihood through mentorship, life skills, and employability programs.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Youth Development',
    impactScore: 88,
    image: 'ngo_051',
    icon: 'Globe',
    verified: true,
    goalAmount: 540000,
    raisedAmount: 310000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_052',
    name: 'Childline India Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child protection and emergency support.',
    description: 'Childline India Foundation provides helpline and emergency response support for vulnerable children in need of protection.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Child Rights',
    impactScore: 91,
    image: 'ngo_052',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 460000,
    raisedAmount: 240000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_053',
    name: 'Salaam Baalak Trust',
    ownerId: 'placeholder_owner',
    shortDescription: 'Street children, education, and shelter.',
    description: 'Salaam Baalak Trust supports street children with shelter, education, healthcare, and reintegration services.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Child Rights',
    impactScore: 89,
    image: 'ngo_053',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 380000,
    raisedAmount: 190000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_054',
    name: 'Prayas',
    ownerId: 'placeholder_owner',
    shortDescription: 'Children and trafficking prevention.',
    description: 'Prayas works with vulnerable children and youth through shelter, rehabilitation, education, and anti-trafficking efforts.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Child Rights',
    impactScore: 85,
    image: 'ngo_054',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 340000,
    raisedAmount: 150000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_055',
    name: 'Seva Mandir',
    ownerId: 'placeholder_owner',
    shortDescription: 'Rural development and community support.',
    description: 'Seva Mandir partners with rural communities on education, livelihoods, health, and participatory village development.',
    city: 'Udaipur',
    state: 'Rajasthan',
    cause: 'Rural Development',
    impactScore: 89,
    image: 'ngo_055',
    icon: 'Globe',
    verified: true,
    goalAmount: 500000,
    raisedAmount: 275000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_056',
    name: 'Maher',
    ownerId: 'placeholder_owner',
    shortDescription: 'Care for women and children.',
    description: 'Maher provides shelter, care, and rehabilitation for women and children in vulnerable and abusive situations.',
    city: 'Pune',
    state: 'Maharashtra',
    cause: 'Women Empowerment',
    impactScore: 86,
    image: 'ngo_056',
    icon: 'Globe',
    verified: true,
    goalAmount: 360000,
    raisedAmount: 180000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_057',
    name: 'Maitri',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child malnutrition and maternal support.',
    description: 'Maitri focuses on child nutrition, maternal health, and community-based support for families at risk of malnutrition.',
    city: 'Kolkata',
    state: 'West Bengal',
    cause: 'Maternal and Child Health',
    impactScore: 84,
    image: 'ngo_057',
    icon: 'Heart',
    verified: true,
    goalAmount: 310000,
    raisedAmount: 145000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_058',
    name: 'Katha',
    ownerId: 'placeholder_owner',
    shortDescription: 'Reading, literacy, and children\'s education.',
    description: 'Katha promotes literacy, reading, and joyful learning experiences for children in underserved communities.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Education',
    impactScore: 85,
    image: 'ngo_058',
    icon: 'BookOpen',
    verified: true,
    goalAmount: 280000,
    raisedAmount: 130000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_059',
    name: 'SERUDS',
    ownerId: 'placeholder_owner',
    shortDescription: 'Children, elderly care, and health.',
    description: 'SERUDS supports children and elderly people with food, healthcare, education, and care-based community services.',
    city: 'Anantapur',
    state: 'Andhra Pradesh',
    cause: 'Community Care',
    impactScore: 83,
    image: 'ngo_059',
    icon: 'Heart',
    verified: true,
    goalAmount: 260000,
    raisedAmount: 120000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_060',
    name: 'SNEHA Mumbai',
    ownerId: 'placeholder_owner',
    shortDescription: 'Maternal and child health support.',
    description: 'SNEHA Mumbai works on maternal health, child health, nutrition, and urban public health for vulnerable communities.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Healthcare',
    impactScore: 87,
    image: 'ngo_060',
    icon: 'Heart',
    verified: true,
    goalAmount: 530000,
    raisedAmount: 275000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_061',
    name: 'Arpan',
    ownerId: 'placeholder_owner',
    shortDescription: 'Child sexual abuse prevention and healing.',
    description: 'Arpan works to prevent child sexual abuse, support survivors, and build safer, more aware communities through training and healing services.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Child Protection',
    impactScore: 88,
    image: 'ngo_061',
    icon: 'ShieldCheck',
    verified: true,
    goalAmount: 410000,
    raisedAmount: 200000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_062',
    name: 'Pravah',
    ownerId: 'placeholder_owner',
    shortDescription: 'Youth leadership and civic engagement.',
    description: 'Pravah empowers young people to lead social change through civic engagement, leadership development, and community action.',
    city: 'New Delhi',
    state: 'Delhi',
    cause: 'Youth Development',
    impactScore: 84,
    image: 'ngo_062',
    icon: 'Globe',
    verified: true,
    goalAmount: 300000,
    raisedAmount: 150000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_063',
    name: 'Rang De',
    ownerId: 'placeholder_owner',
    shortDescription: 'Microfinance and livelihood support.',
    description: 'Rang De uses peer-to-peer lending to support entrepreneurs and families with low-cost capital for livelihoods and growth.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Livelihoods',
    impactScore: 89,
    image: 'ngo_063',
    icon: 'Globe',
    verified: true,
    goalAmount: 520000,
    raisedAmount: 310000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_064',
    name: 'Selco India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Clean energy access and livelihoods.',
    description: 'Selco India brings clean energy solutions to low-income households and livelihood users to improve productivity and dignity.',
    city: 'Bengaluru',
    state: 'Karnataka',
    cause: 'Environment',
    impactScore: 91,
    image: 'ngo_064',
    icon: 'TreePine',
    verified: true,
    goalAmount: 640000,
    raisedAmount: 390000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_065',
    name: 'Srijan Foundation',
    ownerId: 'placeholder_owner',
    shortDescription: 'Rural development, water, and sanitation.',
    description: 'Srijan Foundation supports rural communities with water, sanitation, health, and livelihood interventions.',
    city: 'Patna',
    state: 'Bihar',
    cause: 'Rural Development',
    impactScore: 85,
    image: 'ngo_065',
    icon: 'Globe',
    verified: true,
    goalAmount: 330000,
    raisedAmount: 160000,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ngo_066',
    name: 'Aga Khan Foundation India',
    ownerId: 'placeholder_owner',
    shortDescription: 'Rural development, health, and education.',
    description: 'Aga Khan Foundation India works with communities to improve education, health, and rural development through long-term partnerships.',
    city: 'Mumbai',
    state: 'Maharashtra',
    cause: 'Rural Development',
    impactScore: 92,
    image: 'ngo_066',
    icon: 'Globe',
    verified: true,
    goalAmount: 850000,
    raisedAmount: 490000,
    createdAt: new Date().toISOString(),
  },
];